package utilities;

public enum Specialization {

	AUDIOLOGIST,
	ALLERGIST,
	ANESTHESIOLOGIST,
	CARDIOLOGIST,
	DENTIST,
	DERMATOLOGIST,
	ENDOCRINOLOGIST,
	EPIDEMIOLOGIST,
	GYNECOLOGIST,
	IMMUNOLOGIST,  
	GENETICIST,
	MICROBIOLOGIST,
	NEONATOLOGIST,
	NEUROLOGIST,
	NEUROSURGEON,
	OBSTETRICIAN,
	ONCOLOGIST,
	ORTHOPEDIST,
	PEDIATRICIAN,
	PHYSIOLOGIST,
	PODIATRIST,
	PSYCHIATRIST,
	RADIOLOGIST,
	RHEUMATOLOGIST,
	SURGEON,
	UROLOGIST
}
